import { Listing, Channel } from './types';

export const channels: Channel[] = [
  { id: '1', name: 'Авито', type: 'board', icon: '🟢', color: '#61DAFB', subscribers: undefined, enabled: true },
  { id: '2', name: 'ЦИАН', type: 'board', icon: '🔵', color: '#0066FF', subscribers: undefined, enabled: true },
  { id: '3', name: 'Яндекс.Недвижимость', type: 'board', icon: '🟡', color: '#FFCC00', subscribers: undefined, enabled: false },
  { id: '4', name: 'Домклик', type: 'board', icon: '🔴', color: '#FF5252', subscribers: undefined, enabled: true },
  { id: '5', name: 'Telegram: Недвижимость МСК', type: 'telegram', icon: '💬', color: '#0088CC', subscribers: 15200, enabled: true },
  { id: '6', name: 'Telegram: Квартиры СПб', type: 'telegram', icon: '💬', color: '#0088CC', subscribers: 8400, enabled: true },
  { id: '7', name: 'Telegram: Аренда Москва', type: 'telegram', icon: '💬', color: '#0088CC', subscribers: 22100, enabled: false },
  { id: '8', name: 'Telegram: Элитная недвижимость', type: 'telegram', icon: '💬', color: '#0088CC', subscribers: 5600, enabled: true },
];

export const listings: Listing[] = [
  {
    id: '1',
    title: '2-комн. квартира, 65 м²',
    description: 'Светлая двухкомнатная квартира с ремонтом в новом доме. Панорамные окна, вид на парк. Рядом метро, школа, детский сад.',
    price: 12500000,
    area: 65,
    rooms: 2,
    address: 'Москва, ул. Ленина 45, кв. 12',
    images: [],
    type: 'sale',
    propertyType: 'apartment',
    status: 'published',
    channels: [channels[0], channels[1], channels[4], channels[5]],
    createdAt: '2024-01-15',
    views: 1240,
    contacts: 34,
  },
  {
    id: '2',
    title: '1-комн. квартира, 42 м² — Аренда',
    description: 'Уютная однокомнатная квартира после свежего ремонта. Вся необходимая мебель и техника. Тихий двор, консьерж.',
    price: 55000,
    area: 42,
    rooms: 1,
    address: 'Москва, Пресненская наб. 8',
    images: [],
    type: 'rent',
    propertyType: 'apartment',
    status: 'published',
    channels: [channels[0], channels[3], channels[6]],
    createdAt: '2024-01-18',
    views: 890,
    contacts: 56,
  },
  {
    id: '3',
    title: '3-комн. квартира, 98 м²',
    description: 'Просторная трёшка в ЖК бизнес-класса. Два санузла, гардеробная, подземный паркинг. Охрана, консьерж-сервис.',
    price: 28000000,
    area: 98,
    rooms: 3,
    address: 'Москва, Хамовнический вал 12',
    images: [],
    type: 'sale',
    propertyType: 'apartment',
    status: 'draft',
    channels: [],
    createdAt: '2024-01-20',
    views: 0,
    contacts: 0,
  },
  {
    id: '4',
    title: 'Коммерческое помещение, 120 м²',
    description: 'Помещение свободного назначения на первой линии. Витринные окна, высокий трафик. Подходит под магазин, офис, салон.',
    price: 85000,
    area: 120,
    rooms: 0,
    address: 'Москва, Тверская ул. 28',
    images: [],
    type: 'rent',
    propertyType: 'commercial',
    status: 'published',
    channels: [channels[0], channels[1], channels[2], channels[7]],
    createdAt: '2024-01-10',
    views: 567,
    contacts: 12,
  },
];